### ISSUE TITLE
v 3.128.2 not working

### ISSUE THREAD

**Issue by ddaanniiieeelll** [typemytype/drawBotRoboFontExtension#12]
Hello,

I recently updated to v 3.128.2 through Mechanic. This version does not work at all with my setup.

After updating through mechanic and using a script importing DrawBot I get 

```
Traceback (most recent call last):
  File "exportDrawings.py", line 2, in <module>
ModuleNotFoundError: No module named 'drawBot'
```

Checking out in the packages manager there is indeed no DrawBot module installed.

Tried to de- / re-install through mechanic and got this error

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "/Users/daniel/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBotController.py", line 11, in <module>
  File "/Users/daniel/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBot/__init__.py", line 1, in <module>
  File "/Users/daniel/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBot/drawBotDrawingTools.py", line 10, in <module>
  File "/Users/daniel/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBot/context/__init__.py", line 8, in <module>
  File "/Users/daniel/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBot/context/imageObjectContext.py", line 1, in <module>
ModuleNotFoundError: No module named 'PIL'
```

Checking out the previous version works again as expected.

OS Monterey 12.0.1
RF Version 4.1 (build 2111241049)

**Comment by typemytype** [comment]
oh I see... 

for now you can install `pillow` in RoboFont [pipinstaller](https://robofont.com/documentation/reference/workspace/package-installer/)
