### ISSUE TITLE
traceImage() not working in RF DB extension

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawBotRoboFontExtension#3]
```
('/bin/sh: /Users/just/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBot/context/tools/mkbitmap: Permission denied\n', '')
('/bin/sh: /Users/just/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBot/context/tools/potrace: Permission denied\n', '')
Traceback (most recent call last):
  File "<untitled>", line 30, in <module>
  File "/Users/just/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBot/context/baseContext.py", line 219, in traceImage
    traceImage.TraceImage(path, self, threshold, blur, invert, turd, tolerance, offset)
  File "/Users/just/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBot/context/tools/traceImage.py", line 337, in TraceImage
    importSVGWithPen(svgPath, outPen, (x, y, w, h), offset)
  File "/Users/just/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBot/context/tools/traceImage.py", line 213, in importSVGWithPen
    svgDoc = minidom.parse(svgPath)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/minidom.py", line 1918, in parse
    return expatbuilder.parse(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/expatbuilder.py", line 922, in parse
    fp = open(file, 'rb')
IOError: [Errno 2] No such file or directory: '/var/folders/r6/16l72gg51gqcwbgpk9gtv0mc0000gn/T/tmp_SY4Pq.svg'
```

**Comment by typemytype** [comment]
have to set the chmod of those two executable files correctly when the extension gets installed

similar as what already happens for gifsicle

**Comment by typemytype** [comment]
this should fix it
https://github.com/typemytype/drawBotRoboFontExtension/commit/42e24ba0517b49560e75d21feb9500219a1b5be6

**Comment by justvanrossum** [comment]
It does. Thanks!
