### ISSUE TITLE
writing animated gif or mp4 fails on a freshly installed DB extension

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawBotRoboFontExtension#5]
```python
newPage(400, 400)
rect(50, 50, 200, 200)
newPage(400, 400)
rect(150, 150, 200, 200)

saveImage("~/Desktop/mydumbtestgif.gif")
```

```
Traceback (most recent call last):
  File "<untitled>", line 6, in <module>
  File "/var/folders/r6/16l72gg51gqcwbgpk9gtv0mc0000gn/T/tmpAX9RZf/drawBotRoboFontExtension-master/DrawBot.roboFontExt/lib/drawBot/drawBotDrawingTools.py", line 437, in saveImage
  File "/var/folders/r6/16l72gg51gqcwbgpk9gtv0mc0000gn/T/tmpAX9RZf/drawBotRoboFontExtension-master/DrawBot.roboFontExt/lib/drawBot/context/baseContext.py", line 1845, in saveImage
  File "/var/folders/r6/16l72gg51gqcwbgpk9gtv0mc0000gn/T/tmpAX9RZf/drawBotRoboFontExtension-master/DrawBot.roboFontExt/lib/drawBot/context/pdfContext.py", line 67, in _saveImage
  File "/var/folders/r6/16l72gg51gqcwbgpk9gtv0mc0000gn/T/tmpAX9RZf/drawBotRoboFontExtension-master/DrawBot.roboFontExt/lib/drawBot/context/gifContext.py", line 49, in _writeDataToFile
  File "/var/folders/r6/16l72gg51gqcwbgpk9gtv0mc0000gn/T/tmpAX9RZf/drawBotRoboFontExtension-master/DrawBot.roboFontExt/lib/drawBot/context/tools/gifTools.py", line 40, in generateGif
  File "/var/folders/r6/16l72gg51gqcwbgpk9gtv0mc0000gn/T/tmpAX9RZf/drawBotRoboFontExtension-master/DrawBot.roboFontExt/lib/drawBot/misc.py", line 307, in executeExternalProcess
  File "subprocess.pyc", line 710, in __init__
  File "subprocess.pyc", line 1335, in _execute_child
OSError: [Errno 2] No such file or directory
```

So to be clear: this error happens in the following sequence of events:

- start RF 1.8.4 with no DB extension installed
- install the DrawBot extension (3.112) via Mechanik
- run the above script
- find traceback

Restarting RF fixes the problem.
Saving other formats (that don't need an external process) works fine.

**Comment by justvanrossum** [comment]
The location of the source files in the tb looks very suspicious to me.

**Comment by typemytype** [comment]
Mechanic is downloading them into a temp folder and is installing them from that temp folder. Start up scripts are executed from the same temp folder. 

Mechanic removes that temp folder so those paths to external tools like mpeg does not exists anymore.

A RoboFont restart will indeed resolved this issue...

(this issue is solved in the next update of RF...)
